package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
/**
 *
 * @author Asus
 */
public class InformacionEquipo extends javax.swing.JFrame {

    int IDcliente_update = 0, IDequipo = 0;
    String user = "", nom_cliente = "";
    /**
     * Creates new form InformacionEquipo
     */
    public InformacionEquipo() {
        initComponents();
        user = Login.user;
        IDequipo = InformacionCliente.IDequipo;
        IDcliente_update = GestionarClientes.IDcliente_update;
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                "select nombre_cliente from clientes where id_cliente = '" + IDcliente_update + "'");
            
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                nom_cliente = rs.getString("nombre_cliente");
                
            }
            
        } catch (SQLException e) {
            System.err.println("Error al consultar el nombre del cliente");
        }
        txtNombreCliente.setText(nom_cliente);
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                "select * from equipos where id_equipo = '" + IDequipo + "'");
            
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                
                cmbTipoEquipo.setSelectedItem(rs.getString("tipo_equipo"));
                cmbMarca.setSelectedItem(rs.getString("marca"));
                cmbEstatus.setSelectedItem(rs.getString("estatus"));
                txtModelo.setText(rs.getString("modelo"));
                txtNumSerie.setText(rs.getString("num_serie"));
                txtUltimaModificacion.setText(rs.getString("ultima_modificacion"));
                
                String dia = "", mes = "", annio = "";
                dia = rs.getString("dia_ingreso");
                mes = rs.getString("mes_ingreso");
                annio = rs.getString("annio_ingreso");
                txtFecha.setText(dia + " del " + mes + " del " + annio);
                
                txtpObservaciones.setText(rs.getString("observaciones"));
                txtpComentariosTecnicos.setText(rs.getString("comentarios_tecnicos"));
                labelrevisiontecnicade.setText("Comentarios y actualización del técnico: " + rs.getString("revision_tecnica_de"));
            }
            
        } catch (SQLException e) {
            System.err.println("Error al consultar la información del equipo " + e);
        }
        
        setTitle("Equipo del cliente " + nom_cliente);
        setSize(670, 530);
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(labelWallpaper.getWidth(),
                labelWallpaper.getHeight(), Image.SCALE_DEFAULT));
        labelWallpaper.setIcon(icono);
        this.repaint();
        
        
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelNombre1 = new javax.swing.JLabel();
        labelNombre2 = new javax.swing.JLabel();
        labelNombre3 = new javax.swing.JLabel();
        labelNombre4 = new javax.swing.JLabel();
        labelNombre5 = new javax.swing.JLabel();
        labelNombre6 = new javax.swing.JLabel();
        labelNombre7 = new javax.swing.JLabel();
        labelNombre8 = new javax.swing.JLabel();
        labelrevisiontecnicade = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtNumSerie = new javax.swing.JTextField();
        txtUltimaModificacion = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        cmbEstatus = new javax.swing.JComboBox<>();
        cmbTipoEquipo = new javax.swing.JComboBox<>();
        cmbMarca = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpObservaciones = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtpComentariosTecnicos = new javax.swing.JTextPane();
        btnActualizar = new javax.swing.JButton();
        labelFooter = new javax.swing.JLabel();
        labelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Información de equipo");
        getContentPane().add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        labelNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText("Nombre del cliente:");
        getContentPane().add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        labelNombre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre1.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre1.setText("Tipo de quipo:");
        getContentPane().add(labelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        labelNombre2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre2.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre2.setText("Marca:");
        getContentPane().add(labelNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        labelNombre3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre3.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre3.setText("Modelo:");
        getContentPane().add(labelNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        labelNombre4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre4.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre4.setText("Número de serie:");
        getContentPane().add(labelNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        labelNombre5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre5.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre5.setText("Fecha de Ingreso:");
        getContentPane().add(labelNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        labelNombre6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre6.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre6.setText("Ultima Modificación por:");
        getContentPane().add(labelNombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        labelNombre7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre7.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre7.setText("Estatus:");
        getContentPane().add(labelNombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        labelNombre8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre8.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre8.setText("Daño reportado y Observaciones:");
        getContentPane().add(labelNombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        labelrevisiontecnicade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelrevisiontecnicade.setForeground(new java.awt.Color(255, 255, 255));
        labelrevisiontecnicade.setText("Comentarios y Actualización de Técnico:");
        getContentPane().add(labelrevisiontecnicade, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setBackground(new java.awt.Color(153, 153, 255));
        txtNombreCliente.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtNombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, -1));

        txtModelo.setBackground(new java.awt.Color(153, 153, 255));
        txtModelo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtModelo.setForeground(new java.awt.Color(255, 255, 255));
        txtModelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtModelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, -1));

        txtNumSerie.setBackground(new java.awt.Color(153, 153, 255));
        txtNumSerie.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtNumSerie.setForeground(new java.awt.Color(255, 255, 255));
        txtNumSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumSerie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 210, -1));

        txtUltimaModificacion.setEditable(false);
        txtUltimaModificacion.setBackground(new java.awt.Color(153, 153, 255));
        txtUltimaModificacion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtUltimaModificacion.setForeground(new java.awt.Color(255, 255, 255));
        txtUltimaModificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUltimaModificacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtUltimaModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 210, -1));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(153, 153, 255));
        txtFecha.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 180, -1));

        cmbEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo ingreso", "No reparado", "En revisión", "Reparado", "Entregado" }));
        cmbEstatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cmbEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        cmbTipoEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Desktop", "Impresora", "Multifuncional", "Celular" }));
        cmbTipoEquipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cmbTipoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        cmbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acer", "Alinware", "Apple", "Asus", "Brother", "Dell", "HP", "Lenovo", "Samsung", "Toshiba", "Xerox" }));
        cmbMarca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cmbMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jScrollPane1.setViewportView(txtpObservaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 330, 120));

        txtpComentariosTecnicos.setEditable(false);
        jScrollPane2.setViewportView(txtpComentariosTecnicos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 330, 120));

        btnActualizar.setBackground(new java.awt.Color(153, 153, 255));
        btnActualizar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar equipo");
        btnActualizar.setBorder(null);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 210, 35));

        labelFooter.setText("Creado Por Angelo Rojas ®");
        getContentPane().add(labelFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, -1, -1));
        getContentPane().add(labelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        int validacion = 0;
        String tipo_equipo, marca, modelo, num_serie, estatus, observaciones;
        
        tipo_equipo = cmbTipoEquipo.getSelectedItem().toString();
        marca = cmbMarca.getSelectedItem().toString();
        estatus = cmbEstatus.getSelectedItem().toString();
        
        modelo = txtModelo.getText().trim();
        num_serie = txtNumSerie.getText().trim();
        observaciones = txtpObservaciones.getText();
        
        if (modelo.equals("")) {
            
            txtModelo.setBackground(Color.red);
            validacion++;
        }
        if (num_serie.equals("")) {
            
            txtNumSerie.setBackground(Color.red);
            validacion++;
        }
        if (observaciones.equals("")) {
            txtpObservaciones.setText("Sin Observaciones.");
        }
        
        if (validacion == 0) {
            
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "update equipos set tipo_equipo=?, marca=?, modelo=?, num_serie=?, observaciones=?, estatus=?, ultima_modificacion=? "
                                + "where id_equipo = '" + IDequipo + "'");
                
                pst.setString(1, tipo_equipo);
                pst.setString(2, marca);
                pst.setString(3, modelo);
                pst.setString(4, num_serie);
                pst.setString(5, observaciones);
                pst.setString(6, estatus);
                pst.setString(7, user);
                
                pst.executeUpdate();
                cn.close();
                
                Limpiar();
                
                txtNombreCliente.setBackground(Color.green);
                txtModelo.setBackground(Color.green);
                txtNumSerie.setBackground(Color.green);
                txtFecha.setBackground(Color.green);
                txtUltimaModificacion.setText(user);
                
                JOptionPane.showMessageDialog(null, "Actualización correcta.");
                this.dispose();
                
            } catch (SQLException e) {
                System.err.println("Error al actualizar datos del equipo. " + e);
                JOptionPane.showMessageDialog(null, "!!Error al actualizar datos del equipo¡¡ contacte al administrador.");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox<String> cmbEstatus;
    private javax.swing.JComboBox<String> cmbMarca;
    private javax.swing.JComboBox<String> cmbTipoEquipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelFooter;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelNombre2;
    private javax.swing.JLabel labelNombre3;
    private javax.swing.JLabel labelNombre4;
    private javax.swing.JLabel labelNombre5;
    private javax.swing.JLabel labelNombre6;
    private javax.swing.JLabel labelNombre7;
    private javax.swing.JLabel labelNombre8;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelWallpaper;
    private javax.swing.JLabel labelrevisiontecnicade;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNumSerie;
    private javax.swing.JTextField txtUltimaModificacion;
    private javax.swing.JTextPane txtpComentariosTecnicos;
    private javax.swing.JTextPane txtpObservaciones;
    // End of variables declaration//GEN-END:variables

    public void Limpiar(){
        txtNombreCliente.setText("");
        txtFecha.setText("");
        txtModelo.setText("");
        txtNumSerie.setText("");
        txtpObservaciones.setText("");
    }

}
