package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Asus
 */
public class InformacionUsuario extends javax.swing.JFrame {

    String user = "", user_update = "";
    int ID;

    /**
     * Creates new form InfomacionUsuario
     */
    public InformacionUsuario() {
        initComponents();
        user = Login.user;
        user_update = GestionarUsuarios.user_update;

        setSize(630, 450);
        setTitle("Información del Usuario - Sesión de " + user);
        setResizable(false);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(labelWallpaper.getWidth(),
                labelWallpaper.getHeight(), Image.SCALE_DEFAULT));
        labelWallpaper.setIcon(icono);
        this.repaint();

        labelTitulo.setText("Información del Usuario " + user_update);

        //lineas para llenar la información
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select * from usuarios where username = '" + user_update + "'");
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                ID = rs.getInt("id_usuario");
                
                txtNombre.setText(rs.getString("nombre_usuario"));
                txtMail.setText(rs.getString("email"));
                txtTelefono.setText(rs.getString("telefono"));
                txtUsername.setText(rs.getString("username"));
                txtregistradoPor.setText(rs.getString("registrado_por"));
                
                cmbNiveles.setSelectedItem(rs.getString("tipo_nivel"));
                cmbEstatus.setSelectedItem(rs.getString("estatus"));
                
            }
            cn.close();

        } catch (SQLException e) {
            System.err.println("ERROR en cargar al usuario " + e);
            JOptionPane.showMessageDialog(null, "¡¡Error al cargar!! contacte con el Administrador");
        }

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelNombre1 = new javax.swing.JLabel();
        labelNombre2 = new javax.swing.JLabel();
        labelNombre3 = new javax.swing.JLabel();
        labelNombre4 = new javax.swing.JLabel();
        labelNombre5 = new javax.swing.JLabel();
        labelNombre6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtregistradoPor = new javax.swing.JTextField();
        labelFooter = new javax.swing.JLabel();
        cmbEstatus = new javax.swing.JComboBox<>();
        cmbNiveles = new javax.swing.JComboBox<>();
        buttonActualizar = new javax.swing.JButton();
        buttonRestaurarPass = new javax.swing.JButton();
        labelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Información del Usuario");
        getContentPane().add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        labelNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText("Nombre:");
        getContentPane().add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        labelNombre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre1.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre1.setText("Em@il:");
        getContentPane().add(labelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        labelNombre2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre2.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre2.setText("Télefono:");
        getContentPane().add(labelNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        labelNombre3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre3.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre3.setText("Permisos de:");
        getContentPane().add(labelNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        labelNombre4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre4.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre4.setText("Username:");
        getContentPane().add(labelNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        labelNombre5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre5.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre5.setText("Estatus:");
        getContentPane().add(labelNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        labelNombre6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombre6.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre6.setText("Registrado Por:");
        getContentPane().add(labelNombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        txtNombre.setBackground(new java.awt.Color(153, 153, 255));
        txtNombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        txtMail.setBackground(new java.awt.Color(153, 153, 255));
        txtMail.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtMail.setForeground(new java.awt.Color(255, 255, 255));
        txtMail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        txtTelefono.setBackground(new java.awt.Color(153, 153, 255));
        txtTelefono.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, -1));

        txtUsername.setBackground(new java.awt.Color(153, 153, 255));
        txtUsername.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, -1));

        txtregistradoPor.setBackground(new java.awt.Color(153, 153, 255));
        txtregistradoPor.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtregistradoPor.setForeground(new java.awt.Color(255, 255, 255));
        txtregistradoPor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtregistradoPor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtregistradoPor.setEnabled(false);
        getContentPane().add(txtregistradoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 210, -1));

        labelFooter.setText("Creado Por Angelo Rojas ®");
        getContentPane().add(labelFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        cmbEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cmbEstatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cmbEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        cmbNiveles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Capturista", "Tecnico" }));
        cmbNiveles.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cmbNiveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        buttonActualizar.setBackground(new java.awt.Color(153, 153, 255));
        buttonActualizar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        buttonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        buttonActualizar.setText("Actualizar Usuario");
        buttonActualizar.setBorder(null);
        buttonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 210, 35));

        buttonRestaurarPass.setBackground(new java.awt.Color(153, 153, 255));
        buttonRestaurarPass.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        buttonRestaurarPass.setForeground(new java.awt.Color(255, 255, 255));
        buttonRestaurarPass.setText("Restaurar Password");
        buttonRestaurarPass.setBorder(null);
        buttonRestaurarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRestaurarPassActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRestaurarPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 210, 35));
        getContentPane().add(labelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActualizarActionPerformed
        
        int permisos_cmb, estatus_cmb, validacion = 0;
        String nombre, mail, telefono, username, pass, permisos_string = "", estatus_string = "";
        
        mail = txtMail.getText().trim();
        username = txtUsername.getText().trim();
        nombre = txtNombre.getText().trim();
        telefono = txtTelefono.getText().trim();
        permisos_cmb = cmbNiveles.getSelectedIndex() + 1;
        estatus_cmb = cmbEstatus.getSelectedIndex() + 1;
        
        if (mail.equals("")) {
            txtMail.setBackground(Color.red);
            validacion++;
        }
        if (username.equals("")) {
            txtUsername.setBackground(Color.red);
            validacion++;
        }
        if (nombre.equals("")) {
            txtNombre.setBackground(Color.red);
            validacion++;
        }
        if (telefono.equals("")) {
            txtTelefono.setBackground(Color.red);
            validacion++;
        }
        if (validacion == 0) {
            
            if (permisos_cmb == 1) {
                permisos_string = "Administrador";
            } else if (permisos_cmb == 2) {
                permisos_string = "Capturista";
            } else if (permisos_cmb == 3) {
                permisos_string = "Tecnico";
            }
            
            if (estatus_cmb == 1) {
                estatus_string = "Activo";
            } else if (estatus_cmb == 2) {
                estatus_string = "Inactivo";
            }
            
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "select username from usuarios where username = '" + username + "' and not id_usuario = '" + ID + "'");
                ResultSet rs = pst.executeQuery();
                
                if (rs.next()) {
                    
                    txtUsername.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "Nombre de Usuario no disponible.");
                    cn.close();
                    
                } else {
                    
                    Connection cn2 = Conexion.conectar();
                    PreparedStatement pst2 = cn2.prepareStatement(
                        "update usuarios set nombre_usuario=?, email=?, telefono=?, username=?, tipo_nivel=?, estatus=? "
                                + "where id_usuario = '" + ID + "'");
                    
                    pst2.setString(1, nombre);
                    pst2.setString(2, mail);
                    pst2.setString(3, telefono);
                    pst2.setString(4, username);
                    pst2.setString(5, permisos_string);
                    pst2.setString(6, estatus_string);
                    
                    pst2.executeUpdate();
                    cn2.close();
                    
                    JOptionPane.showMessageDialog(null, "Modificación correcta");
                    this.dispose();
                }
                
            } catch (SQLException e) {
                System.err.println("Error al actualizar." + e);
                
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos.");
        }
        
    }//GEN-LAST:event_buttonActualizarActionPerformed

    private void buttonRestaurarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRestaurarPassActionPerformed
        
        RestaurarPassword restaurarpassword = new RestaurarPassword();
        restaurarpassword.setVisible(true);
    }//GEN-LAST:event_buttonRestaurarPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonActualizar;
    private javax.swing.JButton buttonRestaurarPass;
    private javax.swing.JComboBox<String> cmbEstatus;
    private javax.swing.JComboBox<String> cmbNiveles;
    private javax.swing.JLabel labelFooter;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelNombre2;
    private javax.swing.JLabel labelNombre3;
    private javax.swing.JLabel labelNombre4;
    private javax.swing.JLabel labelNombre5;
    private javax.swing.JLabel labelNombre6;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelWallpaper;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtregistradoPor;
    // End of variables declaration//GEN-END:variables
}
